version: '3'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-db:
